env:
  #action_frequency: 60                  # (int): environment executes action at the action_frequency rate
  #physics_frequency: 60                 # (int): physics frequency (1 / physics_timestep for physx)
  device: null # (None or str): specifies the device to be used if running on the gpu with torch backend
  automatic_reset: false # (bool): whether to automatic reset after an episode finishes
  flatten_action_space: false # (bool): whether to flatten the action space as a sinle 1D-array
  flatten_obs_space: false # (bool): whether the observation space should be flattened when generated
  use_external_obs: false # (bool): Whether to use external observations or not
  rearrangement: true #(bool) Whether to be ued to rearrange
  modify_reload_model: true #(bool) Whether to reload model when achieve one epoch
  initial_pos_z_offset: 0.1
  external_sensors: null # (None or list): If specified, list of sensor configurations for external sensors to add. Should specify sensor "type" and any additional kwargs to instantiate the sensor. Each entry should be the kwargs passed to @create_sensor, in addition to position, orientation

render:
  viewer_width: 1280
  viewer_height: 720

scene:
  type: Threed_FRONTScene
  scene_model: hotel_suite_small
  trav_map_resolution: 0.1
  default_erosion_radius: 0.0
  trav_map_with_objects: true
  num_waypoints: 1
  waypoint_resolution: 0.2
  load_object_categories: null
  not_load_object_categories: null
  load_room_types: null
  load_room_instances: null
  seg_map_resolution: 0.1
  scene_source: OG
  include_robots: true

# robots:
#   - type: Turtlebot
#     obs_modalities: [scan, rgb, depth]
#     scale: 1.0
#     self_collision: false
#     action_normalize: true
#     action_type: continuous
#     sensor_config:
#       VisionSensor:
#         sensor_kwargs:
#           image_height: 1024
#           image_width: 1024
#       ScanSensor:
#           sensor_kwargs:
#             min_range: 0.05
#             max_range: 10.0
#     controller_config:
#       base:
#         name: DifferentialDriveController

robots:
  - type: Test
    # obs_modalities: [rgb, depth, depth_linear]
    obs_modalities: [rgb]
    action_normalize: true
    action_type: continuous
    grasping_mode: sticky
    sensor_config:
      VisionSensor:
        sensor_kwargs:
          image_height: 128
          image_width: 128
          # focal_length: 10.0

objects: []

task:
  type: RearrangeDlTask
  robot_idn: 0
  obj_num: 6
  tolerance: 0.30
  initial_pos: null
  initial_quat: null
  termination_config: null
  reward_config: null
